// Bangladesh Divisions and their Areas
export const BANGLADESH_DIVISIONS = [
  "Dhaka",
  "Chittagong",
  "Rajshahi",
  "Khulna",
  "Sylhet",
  "Rangpur",
  "Barisal",
  "Mymensingh",
] as const;

export const BANGLADESH_AREAS: Record<string, string[]> = {
  Dhaka: [
    "Rampura",
    "Badda",
    "Gulshan",
    "Mohammadpur",
    "Dhanmondi",
    "Mirpur",
    "Uttara",
    "Banani",
    "Bashundhara",
    "Tejgaon",
    "Motijheel",
    "Paltan",
    "Shahbag",
    "Ramna",
    "Lalbagh",
    "Kotwali",
    "Sutrapur",
    "Wari",
    "Chawkbazar",
    "Bangshal",
    "Hazrat Shahjalal International Airport Area",
    "Jatrabari",
    "Shyampur",
    "Demra",
    "Sabujbagh",
    "Khilgaon",
    "Cantonment",
    "Kafrul",
    "Pallabi",
    "Adabor",
    "Sher-e-Bangla Nagar",
    "Darussalam",
    "Turf Ground",
    "Gendaria",
    "Sutrapur",
    "Kamrangirchar",
    "Old Dhaka",
    "Wari",
    "Gulshan-1",
    "Gulshan-2",
    "Baridhara",
    "Banani DOHS",
    "Nikunja",
    "Vatara",
    "Khilkhet",
    "Beraid",
    "Harirampur",
    "Matuail",
    "Shyampur",
    "Sarulia",
    "Dakshin Khan",
    "Uttar Khan",
    "Biman Bandar",
    "Hazaribagh",
    "Shah Ali",
    "Shahjadpur",
    "Tolarbagh",
    "Paikpara",
    "Kazipara",
    "Shewrapara",
    "Pirerbagh",
    "Ibrahimpur",
    "Kalachandpur",
    "Bashabo",
    "Mugdapara",
    "Maniknagar",
    "Basabo",
    "Madartek",
    "Nandipara",
    "Moghbazar",
    "Malibagh",
    "Rajarbagh",
    "Naya Bazar",
    "Azimpur",
    "Farminggate",
    "Katabon",
    "Nilkhet",
    "New Market",
    "Dholaikhal",
    "Gopibagh",
    "Jaykaturpara",
    "Mazar Gate",
    "Kamalapur",
    "Saydabad",
    "Nayabazar",
    "Tantibazar",
    "Banglabazar",
    "Narinda",
    "Sutrapur",
    "Faridabad",
    "Gandaria",
    "Wiseghat",
    "Sadharghat",
    "Bangla Bazar",
    "Churihatta",
    "Naya Bazar",
    "Tati Bazar",
    "English Road",
    "Johnson Road",
    "Nazimuddin Road",
    "Aga Masih Lane",
    "Begun Bazar",
    "Razia Square",
    "Rahmatullah Market",
    "Hawkers Market",
    "Polton Super Market",
    "Kawran Bazar",
    "Karwan Bazar",
    "Tejkunipara",
    "Monipuripara",
    "Indira Road",
    "Manik Mia Avenue",
    "Road No. 27 Dhanmondi",
    "Road No. 32 Dhanmondi",
    "Dhanmondi R/A",
    "Satmasjid Road",
    "Mirpur DOHS",
    "ECB Chattar",
    "Cantonment",
    "Pallabi",
    "Section 1 Mirpur",
    "Section 2 Mirpur",
    "Section 3 Mirpur",
    "Section 4 Mirpur",
    "Section 5 Mirpur",
    "Section 6 Mirpur",
    "Section 7 Mirpur",
    "Section 8 Mirpur",
    "Section 9 Mirpur",
    "Section 10 Mirpur",
    "Section 11 Mirpur",
    "Section 12 Mirpur",
    "Section 13 Mirpur",
    "Section 14 Mirpur",
    "Section 15 Mirpur",
    "Rupnagar Mirpur",
    "Kalyanpur",
    "Shia Masjid",
    "Kallyanpur",
    "Pirerbagh",
    "Paikpara",
    "Kazipara",
    "Shewrapara",
    "Tolarbagh",
    "Ibrahimpur",
    "Cantonment",
    "Board Bazar",
    "Zigatola",
    "Dhanmondi",
    "Jigatola",
    "Kalabagan",
    "Sukrabad",
    "Paribagh",
    "Green Road",
    "Panthapath",
    "Farmgate",
    "Katabon",
    "Nilkhet",
    "New Market",
    "Gulistan",
    "Fulbaria",
    "Nayabazar",
    "English Road",
    "Johnson Road",
    "Agargaon",
    "Sher-e-Bangla Nagar",
    "Mirpur",
    "Pallabi",
    "Kafrul",
    "Adabor",
    "Darussalam",
  ],
  Chittagong: [
    "Chawkbazar",
    "Andarkilla",
    "Nasirabad",
    "Agrabad",
    "GEC Circle",
    "Station Road",
    "New Market",
    "Reazuddin Bazar",
    "Kazir Dewri",
    "Firingi Bazar",
    "Patharghata",
    "Chak Bazar",
    "Kadamtali",
    "Bakalia",
    "Sholoshahar",
    "Pahartali",
    "Panchlaish",
    "Khulshi",
    "Jamal Khan",
    "Mehedibagh",
    "Muradpur",
    "Probartak",
    "Golpahar",
    "Dampara",
    "Wasa Gate",
    "Oxygen Circle",
    "2 No Gate",
    "3 No Gate",
    "4 No Gate",
    "Bahoddarhat",
    "Chaktai",
    "Khatunganj",
    "Asadganj",
    "Beparipara",
    "Sarak Bazar",
    "Colonel Hat",
    "Aman Bazar",
    "Shantibagh",
    "Madarbari",
    "Borobazar",
    "Patenga",
    "Halishahar",
    "North Kattali",
    "South Kattali",
    "North Pahartali",
    "South Pahartali",
    "North Agrabad",
    "South Agrabad",
    "East Nasirabad",
    "West Nasirabad",
    "East Sholoshahar",
    "West Sholoshahar",
    "East Bakalia",
    "West Bakalia",
    "North Panchlaish",
    "South Panchlaish",
    "North Khulshi",
    "South Khulshi",
    "Chandgaon",
    "Jamalkhan",
    "Mehedibag",
    "Sholakbahar",
    "Sadar Ghat",
    "Double Mooring",
    "EPZ Area",
    "Kalurghat",
    "Banshkhali",
    "Anwara",
    "Sitakunda",
    "Mirsharai",
    "Sandwip",
    "Hathazari",
    "Raozan",
    "Chandanaish",
    "Boalkhali",
    "Lohagara",
    "Satkania",
    "Karnaphuli",
  ],
  Rajshahi: [
    "Shaheb Bazar",
    "Kazihata",
    "Laxmipur",
    "Motihar",
    "Boalia",
    "Rajpara",
    "Shah Mokhdum",
    "Kadirganj",
    "Sapura",
    "Borobazar",
    "Railgate",
    "Binodpur",
    "Kadirganj",
    "Sagorpara",
    "Uposhahar",
    "Shiroil",
    "Ghoramara",
    "Charghoramara",
    "Nalkara",
    "Horse Race Field",
    "Talaimari",
    "Kazla",
    "Belpukur",
    "Charghat",
    "Bagha",
    "Bagmara",
    "Durgapur",
    "Mohanpur",
    "Paba",
    "Puthia",
    "Tanore",
    "Godagari",
    "Natore",
    "Naogaon",
    "Nawabganj",
  ],
  Khulna: [
    "Shibbari",
    "Boyra",
    "Sonadanga",
    "Daulatpur",
    "Khalishpur",
    "Moylapota",
    "Babu Khan Market",
    "Rupsa",
    "Gallamari",
    "Notun Rasta",
    "Moilapota",
    "Hazi Mohsin Road",
    "KDA Avenue",
    "Jessore Road",
    "Khulna University Area",
    "Shiromoni",
    "Noyabazar",
    "Chittrai",
    "Boro Bazar",
    "Rail Gate",
    "Shonadanga Residential Area",
    "Boyra Residential Area",
    "Daulatpur Residential Area",
    "Khalishpur Residential Area",
    "Bagherhat",
    "Satkhira",
    "Jessore",
    "Magura",
    "Narail",
    "Kushtia",
    "Chuadanga",
    "Meherpur",
    "Jhenaidah",
  ],
  Sylhet: [
    "Zindabazar",
    "Subid Bazar",
    "Dhopadighir Par",
    "Kazir Bazar",
    "Munshipara",
    "Barutkhana",
    "Naiorpool",
    "Taltola",
    "Kumarpara",
    "Mirboxtula",
    "Rikabibazar",
    "Lalbazar",
    "Uttor Surma",
    "Dakshin Surma",
    "Kulgaon",
    "Khaser Maara",
    "Bondar Bazar",
    "Amalshid",
    "Sheola",
    "Osmani Nagar",
    "Balaganj",
    "Bishwanath",
    "Companiganj",
    "Dakshin Surma",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "South Surma",
    "Zakiganj",
    "Moulvibazar",
    "Habiganj",
    "Sunamganj",
  ],
  Rangpur: [
    "Jahaj Company",
    "Keranipara",
    "Sarai Badi",
    "Chawkbazar",
    "Station Road",
    "Rail Gate",
    "Modern More",
    "Medical Mor",
    "Polytechnic Mor",
    "Shapla Chattar",
    "Badriganj",
    "Haragach",
    "Kaunia",
    "Pirgachha",
    "Pirganj",
    "Mithapukur",
    "Sadar",
    "Taraganj",
    "Ulwapur",
    "Gangachara",
    "Rajarhat",
    "Dinajpur",
    "Thakurgaon",
    "Panchagarh",
    "Nilphamari",
    "Lalmonirhat",
    "Kurigram",
    "Gaibandha",
  ],
  Barisal: [
    "Nathullabad",
    "Amanatganj",
    "Charkawa",
    "Bazar Road",
    "Rupatali",
    "Kalibari Road",
    "Kashipur",
    "Sadar Road",
    "Notun Bazar",
    "Charkhalifatabad",
    "Charkalaiya",
    "Charbaria",
    "Charmonai",
    "Bhandaria",
    "Mehendiganj",
    "Muladi",
    "Babuganj",
    "Hizla",
    "Agailjhara",
    "Gournadi",
    "Banaripara",
    "Wazirpur",
    "Uzirpur",
    "Bakerganj",
    "Bhola",
    "Patuakhali",
    "Barguna",
    "Jhalokathi",
    "Pirojpur",
  ],
  Mymensingh: [
    "Notun Bazar",
    "Rail Gate",
    "Charpara",
    "Ganginarpar",
    "Kewatkhali",
    "Sankipara",
    "Chotipara",
    "Borotpara",
    "Borobazar",
    "Thana Ghat",
    "Kachari",
    "Kalu Taki",
    "Muktagacha",
    "Trishal",
    "Valuka",
    "Gauripur",
    "Phulpur",
    "Haluaghat",
    "Dhobaura",
    "Ishwarganj",
    "Nandail",
    "Gaffargaon",
    "Tarakanda",
    "Jamalpur",
    "Sherpur",
    "Netrokona",
  ],
} as const;

// Bangladesh Subjects for Tuition
export const BANGLADESH_SUBJECTS = [
  "Mathematics",
  "Additional Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Science",
  "English",
  "Bangla",
  "Bangladesh and Global Studies",
  "History",
  "Geography",
  "Economics",
  "Accounting",
  "Finance",
  "Business Studies",
  "Computer Science",
  "Information and Communication Technology (ICT)",
  "Agriculture Studies",
  "Home Science",
  "Islamic Studies",
  "Hindu Religion",
  "Christian Religion",
  "Buddhist Religion",
  "Arabic",
  "Sanskrit",
  "Pali",
  "Persian",
  "Urdu",
  "Hindi",
  "Physical Education",
  "Health Science",
  "Art",
  "Music",
  "Sociology",
  "Social Work",
  "Psychology",
  "Logic",
  "Philosophy",
  "Political Science",
  "Civics",
  "Statistics",
  "Higher Mathematics",
  "Environmental Science",
  "Population Education",
  "Climate Change",
  "Disaster Management",
  "Life Oriented Education",
  "Work and Life Oriented Education",
  "Career Education",
] as const;

// Education Levels in Bangladesh
export const BANGLADESH_EDUCATION_LEVELS = [
  "Primary (Class 1-5)",
  "Junior School Certificate (JSC) - Class 6-8",
  "Secondary School Certificate (SSC) - Class 9-10",
  "Higher Secondary Certificate (HSC) - Class 11-12",
  "Alim (Madrasah)",
  "Dakhil (Madrasah)",
  "Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "Medical (MBBS)",
  "Engineering (BSc)",
  "Business Administration (BBA/MBA)",
  "Law (LLB/LLM)",
  "Other",
] as const;

// Class Modes
export const CLASS_MODES = [
  { value: "Online", label: "Online Classes (Zoom/Google Meet)" },
  { value: "Offline", label: "In-Person (Home Tuition)" },
  { value: "Hybrid", label: "Both Online & In-Person" },
  { value: "Coaching", label: "Coaching Center" },
] as const;

// Budget Ranges in BDT
export const BUDGET_RANGES_BDT = [
  { value: "500", label: "৳ 500-800/month" },
  { value: "800", label: "৳ 800-1,200/month" },
  { value: "1200", label: "৳ 1,200-2,000/month" },
  { value: "2000", label: "৳ 2,000-3,000/month" },
  { value: "3000", label: "৳ 3,000-5,000/month" },
  { value: "5000", label: "৳ 5,000-8,000/month" },
  { value: "8000", label: "৳ 8,000-12,000/month" },
  { value: "12000", label: "৳ 12,000+/month" },
  { value: "negotiable", label: "Negotiable" },
] as const;

// Platform Fee (500 BDT)
export const PLATFORM_FEE_BDT = 500;

// Payment Methods
export const PAYMENT_METHODS = [
  { value: "BKASH", label: "bKash", color: "#E2136E", logo: "/bkash-logo.png" },
  { value: "NAGAD", label: "Nagad", color: "#F6921E", logo: "/nagad-logo.png" },
] as const;
